<?php

/*
 *  ACF Pro Fields for UAMS-2016
 */



function my_acf_add_local_field_groups() {

	acf_add_local_field_group(array (
		'key' => 'group_58175352e631a',
		'title' => 'Header Options',
		'fields' => array (
			array (
				'key' => 'field_581755be90f80',
				'label' => 'Instructions / Help',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Instructions go here ...',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_581753bd46f91',
				'label' => 'Desktop Image',
				'name' => '_thumbnail_id',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 1000,
				'min_height' => '',
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_581753c246f92',
				'label' => 'Mobile Image',
				'name' => 'home_image_mobile',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => 800,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_581753c746f93',
				'label' => 'Add Button',
				'name' => 'home_image_add_button',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_581753ca46f94',
				'label' => 'Header Button Text',
				'name' => 'home_image_button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_581753c746f93',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_581753d246f97',
				'label' => 'External',
				'name' => 'home_image_external',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_581753c746f93',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'External URL?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_581753d046f96',
				'label' => 'Button URL',
				'name' => 'home_image_internal_url',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_581753c746f93',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_581753d246f97',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_581753cf46f95',
				'label' => 'Button URL',
				'name' => 'home_image_external_url',
				'type' => 'url',
				'instructions' => 'Include http:// or https://',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_581753c746f93',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_581753d246f97',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-small-hero.php',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-big-hero.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'featured_image',
		),
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_58175656b2921',
		'title' => 'Header Options',
		'fields' => array (
			array (
				'key' => 'field_58175656b9bbe',
				'label' => 'Instructions / Help',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Instructions go here ...',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_58175656b9d52',
				'label' => 'Desktop Image',
				'name' => '_thumbnail_id',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 1000,
				'min_height' => '',
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'featured_image',
		),
		'active' => 1,
		'description' => '',
	));


	acf_add_local_field_group(array (
		'key' => 'group_58138f554ea90',
		'title' => 'Page Options',
		'fields' => array (
			array (
				'key' => 'field_58138f7cb49f6',
				'label' => 'Header Options',
				'name' => 'home_page_slider',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'image' => 'Image with Button',
					'slide' => 'Slider',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fd5dffccc90',
				'label' => 'Action Bar Menu',
				'name' => 'action_menu_active',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show "Action Bar" Menu',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5817b82d8a083',
				'label' => 'Breadcrumbs',
				'name' => 'home_remove_breadcrumbs',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'Remove Breadcrumbs',
				'default_value' => 1,
			),
			array (
				'key' => 'field_58138fd3b49f7',
				'label' => 'Slide Instructions',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'Instructions go here',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_58174c34821a5',
				'label' => 'Image',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_58139eba82205',
				'label' => 'Image Instructions',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'message' => 'Instructions go here ...',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_5813a0328220b',
				'label' => 'Desktop Image',
				'name' => '_thumbnail_id',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 1000,
				'min_height' => '',
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_5813a0658220c',
				'label' => 'Mobile Image',
				'name' => 'home_image_mobile',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => 800,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_58139ee082206',
				'label' => 'Header Title',
				'name' => 'home_image_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 40,
			),
			array (
				'key' => 'field_5813a7828923b',
				'label' => 'Add Button',
				'name' => 'home_image_add_button',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_58139f2482207',
				'label' => 'Header Button Text',
				'name' => 'home_image_button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
						array (
							'field' => 'field_5813a7828923b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58139f5382208',
				'label' => 'External',
				'name' => 'home_image_external',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
						array (
							'field' => 'field_5813a7828923b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'External URL?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_58139fa482209',
				'label' => 'Button URL',
				'name' => 'home_image_internal_url',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58139f5382208',
							'operator' => '!=',
							'value' => '1',
						),
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
						array (
							'field' => 'field_5813a7828923b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_58139fe78220a',
				'label' => 'Button URL',
				'name' => 'home_image_external_url',
				'type' => 'url',
				'instructions' => 'Include http:// or https://',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58139f5382208',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'image',
						),
						array (
							'field' => 'field_5813a7828923b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_58174c86821a7',
				'label' => 'Slideshow',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'slide',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_5813900bb49f8',
				'label' => 'Slides',
				'name' => 'home_slides',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58138f7cb49f6',
							'operator' => '==',
							'value' => 'slide',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_58139038b49f9',
				'min' => 2,
				'max' => 6,
				'layout' => 'block',
				'button_label' => 'Add Slide',
				'sub_fields' => array (
					array (
						'key' => 'field_58139b2c039d0',
						'label' => 'Slide',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array (
						'key' => 'field_58139038b49f9',
						'label' => 'Slide Title / Heading',
						'name' => 'home_slide_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => 24,
					),
					array (
						'key' => 'field_58139468b49fb',
						'label' => 'Text Color',
						'name' => 'home_slide_text_color',
						'type' => 'select',
						'instructions' => 'Choose text color based on image color (ex. Dark text over a bright image)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'lighttext' => 'Light Text',
							'darktext' => 'Dark Text',
						),
						'default_value' => array (
							0 => 'lighttext',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_5813906eb49fa',
						'label' => 'Slide Text',
						'name' => 'home_slide_text',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => 180,
						'rows' => 2,
						'new_lines' => 'br',
					),
					array (
						'key' => 'field_5813c77a5ea67',
						'label' => 'Button Text',
						'name' => 'home_slide_button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => 20,
					),
					array (
						'key' => 'field_581395feb49ff',
						'label' => 'External Link',
						'name' => 'home_slide_external',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_58139644b4a00',
						'label' => 'Internal URL',
						'name' => 'home_slide_internal_link',
						'type' => 'page_link',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_581395feb49ff',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'allow_archives' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_581394d1b49fc',
						'label' => 'External URL',
						'name' => 'home_slide_external_link',
						'type' => 'url',
						'instructions' => 'Include http:// or https://',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_581395feb49ff',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array (
						'key' => 'field_58139535b49fd',
						'label' => 'Desktop Image',
						'name' => 'home_slide_desktop',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => 1000,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 2048,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array (
						'key' => 'field_581395acb49fe',
						'label' => 'Mobile Image',
						'name' => 'home_slide_mobile',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => 800,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array (
				'key' => 'field_58174c65821a6',
				'label' => 'Action Bar',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_58174e04ca0e0',
				'label' => 'Disabled Message',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fd5dffccc90',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'This is disabled, please check the "Add Actionbar" from above',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_57fd5bb2de8d5',
				'label' => 'Action Menu Items',
				'name' => 'action_menu',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fd5dffccc90',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 3,
				'max' => 6,
				'layout' => 'block',
				'button_label' => 'Add Icon',
				'sub_fields' => array (
					array (
						'key' => 'field_57fd5be1de8d6',
						'label' => 'Link Title',
						'name' => 'action_link_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57fd5c20de8d7',
						'label' => 'Link Icon',
						'name' => 'action_link_icon',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'ic-flag' => 'ic-flag',
							'ic-check' => 'ic-check',
							'ic-minus' => 'ic-minus',
							'ic-person' => 'ic-person',
							'ic-plus' => 'ic-plus',
							'ic-camera' => 'ic-camera',
							'ic-mail' => 'ic-mail',
							'ic-search' => 'ic-search',
							'ic-key' => 'ic-key',
							'ic-clipboard' => 'ic-clipboard',
							'ic-bookmark' => 'ic-bookmark',
							'ic-ticket' => 'ic-ticket',
							'ic-heart' => 'ic-heart',
							'ic-watch' => 'ic-watch',
							'ic-letter' => 'ic-letter',
							'ic-marker' => 'ic-marker',
							'ic-social' => 'ic-social',
							'ic-close' => 'ic-close',
							'ic-calendar' => 'ic-calendar',
							'ic-pencil' => 'ic-pencil',
							'ic-computer' => 'ic-computer',
							'ic-page' => 'ic-page',
							'ic-view' => 'ic-view',
							'ic-eating' => 'ic-eating',
							'ic-book' => 'ic-book',
							'ic-stop' => 'ic-stop',
							'ic-compass' => 'ic-compass',
							'ic-home' => 'ic-home',
							'ic-play' => 'ic-play',
							'ic-picture' => 'ic-picture',
							'ic-address-book' => 'ic-address-book',
							'ic-map' => 'ic-map',
							'ic-music' => 'ic-music',
							'ic-settings' => 'ic-settings',
							'ic-tools' => 'ic-tools',
							'ic-globe' => 'ic-globe',
							'ic-briefcase' => 'ic-briefcase',
							'ic-pause' => 'ic-pause',
							'ic-trash' => 'ic-trash',
							'ic-right-arrow-full' => 'ic-right-arrow-full',
							'ic-list' => 'ic-list',
							'ic-page2' => 'ic-page2',
							'ic-right-arrow' => 'ic-right-arrow',
							'ic-podium' => 'ic-podium',
							'ic-directions' => 'ic-directions',
							'ic-capitol' => 'ic-capitol',
							'ic-map-marker' => 'ic-map-marker',
							'ic-passport' => 'ic-passport',
							'ic-administration' => 'ic-administration',
							'ic-plane' => 'ic-plane',
							'ic-handshake' => 'ic-handshake',
							'ic-suitcase' => 'ic-suitcase',
							'ic-globe2' => 'ic-globe2',
							'ic-umbrella' => 'ic-umbrella',
							'ic-ribbon' => 'ic-ribbon',
							'ic-money' => 'ic-money',
							'i-Ambulance' => 'i-Ambulance',
							'i-Blood-Drop' => 'i-Blood-Drop',
							'i-Brain' => 'i-Brain',
							'i-DNA' => 'i-DNA',
							'i-Donate-Blood' => 'i-Donate-Blood',
							'i-Heart-Beat' => 'i-Heart-Beat',
							'i-Heart' => 'i-Heart',
							'i-Hospital-1' => 'i-Hospital-1',
							'i-Hospital-Bed' => 'i-Hospital-Bed',
							'i-Infuzion' => 'i-Infuzion',
							'i-Kidneys' => 'i-Kidneys',
							'i-Liver' => 'i-Liver',
							'i-Lungs' => 'i-Lungs',
							'i-Medical-Bag' => 'i-Medical-Bag',
							'i-Medical-Symbol' => 'i-Medical-Symbol',
							'i-Medicine-Mixing' => 'i-Medicine-Mixing',
							'i-Medicine' => 'i-Medicine',
							'i-Pharmaceutical-Symbol' => 'i-Pharmaceutical-Symbol',
							'i-Pills' => 'i-Pills',
							'i-Skull' => 'i-Skull',
							'i-Stetoscope' => 'i-Stetoscope',
							'i-Stomach' => 'i-Stomach',
							'i-Syringe' => 'i-Syringe',
							'i-Tooth' => 'i-Tooth',
							'i-Weight-Libra' => 'i-Weight-Libra',
							'i-Wheel-Chair' => 'i-Wheel-Chair',
							'i-Addvertise' => 'i-Addvertise',
							'i-Bank-2' => 'i-Bank-2',
							'i-Calculator-1' => 'i-Calculator-1',
							'i-Contact-Info' => 'i-Contact-Info',
							'i-Globe-1' => 'i-Globe-1',
							'i-Handshake' => 'i-Handshake',
							'i-Networking-1' => 'i-Networking-1',
							'i-Networking-2' => 'i-Networking-2',
							'i-Search-Job' => 'i-Search-Job',
							'i-Dumper-Truck' => 'i-Dumper-Truck',
							'i-Excavator-2' => 'i-Excavator-2',
							'i-Nuclear-Symbol' => 'i-Nuclear-Symbol',
							'i-At-Symbol' => 'i-At-Symbol',
							'i-Eatrh-Support' => 'i-Eatrh-Support',
							'i-Business-Man' => 'i-Business-Man',
							'i-Business-Woman' => 'i-Business-Woman',
							'i-Darth-Vader' => 'i-Darth-Vader',
							'i-Dispacher-1' => 'i-Dispacher-1',
							'i-Dispacher-2' => 'i-Dispacher-2',
							'i-Female-1' => 'i-Female-1',
							'i-Male-1' => 'i-Male-1',
							'i-Medic' => 'i-Medic',
							'i-Nurse' => 'i-Nurse',
							'i-Police' => 'i-Police',
							'i-Student' => 'i-Student',
							'i-Waiter' => 'i-Waiter',
							'i-Waitress' => 'i-Waitress',
							'i-Bike' => 'i-Bike',
							'i-Medal-3' => 'i-Medal-3',
							'i-Play' => 'i-Play',
							'i-Favorite' => 'i-Favorite',
							'i-Alambic' => 'i-Alambic',
							'i-Analogue-Antenna' => 'i-Analogue-Antenna',
							'i-Arc-Phisics' => 'i-Arc-Phisics',
							'i-Atom' => 'i-Atom',
							'i-Atomic-Reactor' => 'i-Atomic-Reactor',
							'i-Bacteria-1' => 'i-Bacteria-1',
							'i-Bacteria-4' => 'i-Bacteria-4',
							'i-Binocular' => 'i-Binocular',
							'i-Biohazzard' => 'i-Biohazzard',
							'i-Cronometer' => 'i-Cronometer',
							'i-Flusk-Holder' => 'i-Flusk-Holder',
							'i-Lifting-Phisics' => 'i-Lifting-Phisics',
							'i-Magnet' => 'i-Magnet',
							'i-Magnetic-Field' => 'i-Magnetic-Field',
							'i-Microscope' => 'i-Microscope',
							'i-Molecule-1' => 'i-Molecule-1',
							'i-Molecule-2' => 'i-Molecule-2',
							'i-Multimeter' => 'i-Multimeter',
							'i-Mushroom-Cloud' => 'i-Mushroom-Cloud',
							'i-Newtons-Cradle' => 'i-Newtons-Cradle',
							'i-Observatory' => 'i-Observatory',
							'i-Parabolic-Antena' => 'i-Parabolic-Antena',
							'i-Planet' => 'i-Planet',
							'i-Pulley-Phisics' => 'i-Pulley-Phisics',
							'i-Relativity' => 'i-Relativity',
							'i-Rocket' => 'i-Rocket',
							'i-Satellite' => 'i-Satellite',
							'i-Sextant' => 'i-Sextant',
							'i-Solar-System' => 'i-Solar-System',
							'i-Sputnic' => 'i-Sputnic',
							'i-Tape-Meter' => 'i-Tape-Meter',
							'i-Telescope' => 'i-Telescope',
							'i-Tempometer' => 'i-Tempometer',
							'i-Termometer' => 'i-Termometer',
							'i-Test-Flusk-1' => 'i-Test-Flusk-1',
							'i-Test-Flusk-2' => 'i-Test-Flusk-2',
							'i-Test-Tube' => 'i-Test-Tube',
							'i-Virus-1' => 'i-Virus-1',
							'i-Virus-2' => 'i-Virus-2',
							'i-Minion-1' => 'i-Minion-1',
							'i-Minion-2' => 'i-Minion-2',
							'i-Add-Location' => 'i-Add-Location',
							'i-Clear-Location' => 'i-Clear-Location',
							'i-Compas-Rose' => 'i-Compas-Rose',
							'i-Compass-1' => 'i-Compass-1',
							'i-Compass-2' => 'i-Compass-2',
							'i-Directions' => 'i-Directions',
							'i-Distance-1' => 'i-Distance-1',
							'i-Distance-2' => 'i-Distance-2',
							'i-Done-Location' => 'i-Done-Location',
							'i-Favorit-Location' => 'i-Favorit-Location',
							'i-Global-Position' => 'i-Global-Position',
							'i-Globe' => 'i-Globe',
							'i-Gps-Fixed' => 'i-Gps-Fixed',
							'i-Gps-Not-Fixed' => 'i-Gps-Not-Fixed',
							'i-Gps-Off' => 'i-Gps-Off',
							'i-Home-Location' => 'i-Home-Location',
							'i-Info-Point' => 'i-Info-Point',
							'i-Local-Airport' => 'i-Local-Airport',
							'i-Local-Bank' => 'i-Local-Bank',
							'i-Local-Gas-Station' => 'i-Local-Gas-Station',
							'i-Local-Hospital' => 'i-Local-Hospital',
							'i-Local-Library' => 'i-Local-Library',
							'i-Local-Monument' => 'i-Local-Monument',
							'i-Local-Parking' => 'i-Local-Parking',
							'i-Local-Port' => 'i-Local-Port',
							'i-Local-Pub' => 'i-Local-Pub',
							'i-Local-Restaurant' => 'i-Local-Restaurant',
							'i-Local-Transport' => 'i-Local-Transport',
							'i-Location-1' => 'i-Location-1',
							'i-Location-3' => 'i-Location-3',
							'i-Location-4' => 'i-Location-4',
							'i-Location-A' => 'i-Location-A',
							'i-Location-B' => 'i-Location-B',
							'i-Locatoin-2' => 'i-Locatoin-2',
							'i-Locl-Shop' => 'i-Locl-Shop',
							'i-Map-1' => 'i-Map-1',
							'i-Map-2' => 'i-Map-2',
							'i-Map-3' => 'i-Map-3',
							'i-Map-Pin-1' => 'i-Map-Pin-1',
							'i-Map-Pin-2' => 'i-Map-Pin-2',
							'i-Map-Pin-3' => 'i-Map-Pin-3',
							'i-Map-Pin-4' => 'i-Map-Pin-4',
							'i-Map-pin-5' => 'i-Map-pin-5',
							'i-Map-pin-6' => 'i-Map-pin-6',
							'i-Map-Screen' => 'i-Map-Screen',
							'i-Mobile-Map' => 'i-Mobile-Map',
							'i-Navigation-1' => 'i-Navigation-1',
							'i-Navigation-2' => 'i-Navigation-2',
							'i-Remouve-Location' => 'i-Remouve-Location',
							'i-Street-View' => 'i-Street-View',
							'i-Chat-2' => 'i-Chat-2',
							'i-Chat-3' => 'i-Chat-3',
							'i-Paper-Clip-2' => 'i-Paper-Clip-2',
							'i-Pin' => 'i-Pin',
							'i-Postit' => 'i-Postit',
							'i-Facebook-1' => 'i-Facebook-1',
							'i-Flickr' => 'i-Flickr',
							'i-Instagram' => 'i-Instagram',
							'i-Linkedin' => 'i-Linkedin',
							'i-Pinterest' => 'i-Pinterest',
							'i-Skype' => 'i-Skype',
							'i-Twitter-1' => 'i-Twitter-1',
							'i-Vimeo' => 'i-Vimeo',
							'i-Youtube-1' => 'i-Youtube-1',
							'i-Youtube-2' => 'i-Youtube-2',
							'i-Android' => 'i-Android',
							'i-Apple' => 'i-Apple',
							'i-Chrome' => 'i-Chrome',
							'i-Excel' => 'i-Excel',
							'i-Powerpoint' => 'i-Powerpoint',
							'i-Word' => 'i-Word',
							'i-Celsius' => 'i-Celsius',
							'i-Cloud' => 'i-Cloud',
							'i-Cloudy-Day' => 'i-Cloudy-Day',
							'i-Cloudy-Fog' => 'i-Cloudy-Fog',
							'i-Cloudy-Night' => 'i-Cloudy-Night',
							'i-Cloudy' => 'i-Cloudy',
							'i-Fahrenheit' => 'i-Fahrenheit',
							'i-Fog-day' => 'i-Fog-day',
							'i-Fog-Night' => 'i-Fog-Night',
							'i-Fog' => 'i-Fog',
							'i-Full-Moon' => 'i-Full-Moon',
							'i-Hailstorm-Day' => 'i-Hailstorm-Day',
							'i-Hailstorm-Night' => 'i-Hailstorm-Night',
							'i-Hailstorm' => 'i-Hailstorm',
							'i-Lightning-day' => 'i-Lightning-day',
							'i-Lightning-night' => 'i-Lightning-night',
							'i-Lightning' => 'i-Lightning',
							'i-Moon-2' => 'i-Moon-2',
							'i-Moon-3' => 'i-Moon-3',
							'i-Negative-Temperature' => 'i-Negative-Temperature',
							'i-Pozitive-Temperature' => 'i-Pozitive-Temperature',
							'i-Rain-Day' => 'i-Rain-Day',
							'i-Rain-Night' => 'i-Rain-Night',
							'i-Rain-Storm' => 'i-Rain-Storm',
							'i-Raining' => 'i-Raining',
							'i-Snow-Day' => 'i-Snow-Day',
							'i-Snow-Night' => 'i-Snow-Night',
							'i-Snow-Rain-Day' => 'i-Snow-Rain-Day',
							'i-Snow-Rain-Night' => 'i-Snow-Rain-Night',
							'i-Snow-Rain' => 'i-Snow-Rain',
							'i-Snow' => 'i-Snow',
							'i-Snowing' => 'i-Snowing',
							'i-Star-Night' => 'i-Star-Night',
							'i-Storm-day' => 'i-Storm-day',
							'i-Storm-night' => 'i-Storm-night',
							'i-Sun' => 'i-Sun',
							'i-Temperatur-night' => 'i-Temperatur-night',
							'i-Temperature-Day' => 'i-Temperature-Day',
							'i-Thunder-Storm-Day' => 'i-Thunder-Storm-Day',
							'i-Thunder-Storm-Night' => 'i-Thunder-Storm-Night',
							'i-Thunderstorm' => 'i-Thunderstorm',
							'i-Tornado' => 'i-Tornado',
							'i-Wind' => 'i-Wind',
							'i-Winter-Temperature' => 'i-Winter-Temperature',
							'i-1-Hour' => 'i-1-Hour',
							'i-15-Min' => 'i-15-Min',
							'i-30-Min' => 'i-30-Min',
							'i-45-Min' => 'i-45-Min',
							'i-Alarm-Clock-1' => 'i-Alarm-Clock-1',
							'i-Alarm-Clock-2' => 'i-Alarm-Clock-2',
							'i-Alarm-Clock-3' => 'i-Alarm-Clock-3',
							'i-Alarm-Sound' => 'i-Alarm-Sound',
							'i-Calendar-Clock' => 'i-Calendar-Clock',
							'i-Calendar' => 'i-Calendar',
							'i-Clock-1' => 'i-Clock-1',
							'i-Clock-2' => 'i-Clock-2',
							'i-Digital-Alarm-Clock' => 'i-Digital-Alarm-Clock',
							'i-Old-Clock' => 'i-Old-Clock',
							'i-Sand-Clock' => 'i-Sand-Clock',
							'i-Snooze' => 'i-Snooze',
							'i-Sound-Off' => 'i-Sound-Off',
							'i-Stop-Watch-1' => 'i-Stop-Watch-1',
							'i-Stop-Watch-2' => 'i-Stop-Watch-2',
							'i-Timer-Egg' => 'i-Timer-Egg',
							'i-Update-Time' => 'i-Update-Time',
							'i-Wach-4' => 'i-Wach-4',
							'i-Watch-1' => 'i-Watch-1',
							'i-Watch-2' => 'i-Watch-2',
							'i-Watch-3' => 'i-Watch-3',
							'i-Car-3' => 'i-Car-3',
							'i-Bus-1' => 'i-Bus-1',
							'i-Motorcycle' => 'i-Motorcycle',
							'i-Office-Building' => 'i-Office-Building',
							'i-Sale-Hanger' => 'i-Sale-Hanger',
							'i-Like' => 'i-Like',
							'i-Victory' => 'i-Victory',
							'i-Vote-3' => 'i-Vote-3',
							'i-Camera' => 'i-Camera',
							'i-Map' => 'i-Map',
							'i-Hospital' => 'i-Hospital',
							'i-Hotel-1' => 'i-Hotel-1',
							'i-Hotel-2' => 'i-Hotel-2',
							'i-Hotel-3' => 'i-Hotel-3',
							'i-Hotel-4' => 'i-Hotel-4',
							'i-House-1' => 'i-House-1',
							'i-House-2' => 'i-House-2',
							'i-House-3' => 'i-House-3',
							'i-House-4' => 'i-House-4',
							'i-House-5' => 'i-House-5',
							'i-House-6' => 'i-House-6',
							'i-House-7' => 'i-House-7',
							'i-House-8' => 'i-House-8',
							'i-House-9' => 'i-House-9',
							'i-Office-1' => 'i-Office-1',
							'i-Office-2' => 'i-Office-2',
							'i-Office-3' => 'i-Office-3',
							'i-Office-4' => 'i-Office-4',
							'i-Office-5' => 'i-Office-5',
							'i-Office-6' => 'i-Office-6',
							'i-Pantheon' => 'i-Pantheon',
							'i-Stadium' => 'i-Stadium',
							'i-White-House' => 'i-White-House',
							'i-Disabled-man' => 'i-Disabled-man',
							'i-First-ad' => 'i-First-ad',
							'i-Hand-washing' => 'i-Hand-washing',
							'i-Hot-drink' => 'i-Hot-drink',
							'i-Nuclear' => 'i-Nuclear',
							'i-No-smoking' => 'i-No-smoking',
							'i-Telephone' => 'i-Telephone',
							'i-Male-and-Female-1' => 'i-Male-and-Female-1',
							'i-Male-and-Female-2' => 'i-Male-and-Female-2',
							'i-Male-Circle-1' => 'i-Male-Circle-1',
							'i-Male-Circle-2' => 'i-Male-Circle-2',
							'i-Male-Group-1' => 'i-Male-Group-1',
							'i-Male-Group-2' => 'i-Male-Group-2',
							'i-Name-Plate-Female-1' => 'i-Name-Plate-Female-1',
							'i-Name-Plate-Female-2' => 'i-Name-Plate-Female-2',
							'i-Name-Plate-Female-3' => 'i-Name-Plate-Female-3',
							'i-Name-Plate-Male-1' => 'i-Name-Plate-Male-1',
							'i-Name-Plate-Male-2' => 'i-Name-Plate-Male-2',
							'i-Name-Plate-Male-3' => 'i-Name-Plate-Male-3',
							'i-Portrait-Frame' => 'i-Portrait-Frame',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 1,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_57fd6128b5f60',
						'label' => 'External',
						'name' => 'action_link',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_57fd5c3dde8d8',
						'label' => 'Internal URL',
						'name' => 'action_link_page',
						'type' => 'page_link',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_57fd6128b5f60',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'allow_archives' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_57fd60fab5f5f',
						'label' => 'External URL',
						'name' => 'action_link_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_57fd6128b5f60',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-home.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'featured_image',
		),
		'active' => 1,
		'description' => '',
	));

}

add_action('acf/init', 'my_acf_add_local_field_groups');